import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + 'dark'}>
        <Toaster position="bottom-center"
          // containerStyle={
          //   {
          //     zIndex: 9999,
          //     background: '#00000',
          //     border: '1px solid #ffffff',
          //     boxShadow: '0 0 10px #ffffff'
          //   }
          // } 
          toastOptions={{
            className: '',
            style: {
              border: '1px solid #713200',
              padding: '16px',
              color: '#713200',
            },
          }}
          />
        {children}
      </body>
    </html>
  );
}
